### ISSUE TITLE
Is negate not working?

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortGenerator#111]
https://github.com/OHDSI/CohortGenerator/blob/8379cb8f0b0a089589e6b14be52b752dc687afc6/R/Subsets.R#L406

**Comment by anthonysena** [comment]
This is a documentation bug; the implementation is complete. As evidence, [here](https://github.com/OHDSI/CohortGenerator/blob/8379cb8f0b0a089589e6b14be52b752dc687afc6/inst/sql/sql_server/subsets/CohortSubsetOperator.sql) is the query that uses the parameter.
