### ISSUE TITLE
Limit subset requires > 0 follow up time

### ISSUE THREAD

**Issue by chrisknoll** [OHDSI/CohortGenerator#112]
I'm trying to limit the cohort to those with a required prior observation time, so I set somethign like priorTime = 30.   I don't care about follow up so I make it 0.

I receive an error:  `If specifying observation prior time, must specifcy follow up time`

This is done by this statement in CreateLimitSubset:

```
  if ((is.null(limitTo) | limitTo == "") & (priorTime > 0 | followUpTime > 0)) {
    stop("If specifying observation prior time, must specifcy follow up time")
  }
```

What is confusing here is the requirement of limitTo must be non empty.   I'm not sure what the requrement is that you must limit to first in order to limit the subset with prior obs.   Is that required? I'd like to just only use cohort episodes with prior obs.

**Comment by anthonysena** [comment]
@chrisknoll - I'm interpreting the use-case here as "preserve all cohort events where the prior observation time >= 30 days". Do I have this right? At the moment, the limit subset requires you to decide how you want to limit based on the first/earliest/latest/last event. But in this case you want 'all' that meet the criteria? Just want to confirm so we can consider an extension to this operator to support this. Feels related to #109.

**Comment by azimov** [comment]
The PR I created now has a default behaviour of "all" events per person and removes the condition regarding prior/follow up time
