### ISSUE TITLE
Description needs updated versions for readr and stringi

### ISSUE THREAD

**Issue by jreps** [OHDSI/CohortGenerator#13]
I had readr version 1.4.0 that seems to be a valid version per the Description file (>= 1.4.0) but was getting an error with the input: lazy to read::red_csv. Updating readr fixed this.

Then I got an error "Error: 'stri_sprintf' is not an exported object from 'namespace:stringi'".  This seems to be due to stringi requiring a version > what I have but this is not in the Description.

I think the Description needs to have the readr minimum version requirement set to a higher value and the stringi minimum version requirements specified.

**Comment by anthonysena** [comment]
Thanks @jreps - looking into it, `readr` requires 2.0 or higher and `stringi` should be using the latest (v1.7.6).
