### ISSUE TITLE
'priorTime' failed

### ISSUE THREAD

**Issue by ericaVoss** [OHDSI/CohortGenerator#180]
CohortGenerator 0.10.0

I am trying to use subsetter, specifically CohortGenerator::createLimitSubset(), to limit my cohort to a certain time period.  Here is how I was attempting to use it.

```R
.cohortTime <-
  CohortGenerator::createLimitSubset(
  name = "index between 2010-2022, 180d prior observation time",
  priorTime = -180,
  followUpTime = 0,
  limitTo = "all",
  calendarStartDate = '01/01/2010',
  calendarEndDate = '12/31/2022'
)
```

However, without event using it, just trying to build with the call in my package, I'm getting 
```text
Error in (function (priorTime)  : 
  Assertion on 'priorTime' failed: Element 1 is not >= 0.
Error: unable to load R code in package 'epi11'
Execution halted
ERROR: lazy loading failed for package 'epi11'
```
Is this the proper way to subset a cohort to a certain time period? I couldn't decide if this was a user issue or a bug, but decided to post here over the forum.

It seems to not like my negative 180.  Am I just supposed to say prior time is +180?

**Comment by ericaVoss** [comment]
Okay, it didn't like the "-"s in name or priorTime.  This works.

```R
.cohortTime <-
  CohortGenerator::createLimitSubset(
  name = "index between 2010 to 2022, 180d prior observation time",
  priorTime = 180,
  followUpTime = 0,
  limitTo = "all",
  calendarStartDate = '01/01/2010',
  calendarEndDate = '12/31/2022'
)
```

**Comment by ericaVoss** [comment]
This finally worked for me:

```R
.cohortTime <-
  CohortGenerator::createLimitSubset(
  name = "index between 2010 to 2022, 180d prior observation time",
  priorTime = 180,
  followUpTime = 0,
  limitTo = "all",
  calendarStartDate = '2010/01/01',
  calendarEndDate = '2022/12/31'
)
```

**Comment by anthonysena** [comment]
Yes, this value should be positive as you noted. I'll update the documentation accordingly. Thanks!
