### ISSUE TITLE
Can we add a function to export human readable cohort definitions in to an editable document format like word

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortGenerator#20]
A commonly performed activity is to export cohortDefinitionSet (rendered into human readable text by Circe) into an editable word document that is part of a protocol.

We have the code, but would be interested to give it a home in CohortGenerator.

Would that fit in CohortGenerator?

**Comment by chrisknoll** [comment]
Why not use the printFriendly function of CirceR?  I don't think cohortGenerator has any specific dependency on CirceR (except for in the Suggests, but is that for testing?)  My understanding is that cohort generator was a little removed from the specific implementation that build the cohort generation queries, but @anthonysena  can speak to that better than I could.

The output of CirceR is to create a markdown document, can't you go from markdown into Word/PDF/HTML?

**Comment by gowthamrao** [comment]
> output of CirceR is to create a markdown document, can't you go from markdown into Word/PDF/HTML?

Sure, we talking about something that does the following

1) takes cohort definition set as input
2) creates the markdown using circe for every cohort json in the cohort definition set
3) takes parameters that are needed for the bookdown _yml files.
4) accepts the path to MS word file that is the template
5) accepts additional parameters for fitting tables

outputs a word document, pdf document or html page with a table of contents.


We do this routinely - why not make it easy

**Comment by chrisknoll** [comment]
No, it doesn't belong in CirceR: again, we extract the cohort definition as markdown so that it can be consumed in a variety of sources.  This thing you are describing isn't a Circe function...and it doesn't sound like it's a cohort generation function...do we have a package of utlity functions? This would seem to be a sort of documentation function.

**Comment by gowthamrao** [comment]
ok ! i am not giving you my code for sure @chrisknoll  :)

**Comment by anthonysena** [comment]
Closing since this is out of scope for CohortGenerator.
