### ISSUE TITLE
Use snake case for exportCohortStatsTables data

### ISSUE THREAD

**Issue by anthonysena** [OHDSI/CohortGenerator#23]
`exportCohortStatsTables` is currently exporting data in camel case and instead we should use snake case for consistency with other OHDSI packages.

**Comment by anthonysena** [comment]
Need to check with @azimov on the impact of this change to cohort diagnostics. We should aim to have a central function for exporting results to .csv across the HADES packages.

**Comment by azimov** [comment]
Yes, this will impact all versions of cohort diagnostics above 2.2.x.

My preference would be to have a change like this only impact version 3.0.0 (which should be released soon) onwards.

Also note that CohortDiagnostics could also benefit from functionality of not having to read this data from files but exported from the tables directly.

**Comment by anthonysena** [comment]
Thanks @azimov for the quick reply. Yes, I'd like to do this so that we don't impact CohortDiagnostics < v3.0.0. I'm also looking at the methods in CohortDiagnostics' Incremental.R file and think that perhaps we should aim to move these into CohortGenerator. Specifically the methods where we write to CSV:

https://github.com/OHDSI/CohortDiagnostics/blob/main/R/Incremental.R#L144-L222

Since the code from CohortDiagnostics was the basis for the code that is now in CohortGenerator, perhaps we should re-locate this functionality to CohortGenerator? I would prefer if we are all using the same methods for writing to CSV since this will impact how we handle the upload of these results.

Also happy to address any changes that make it easier for CohortDiagnostics to read from tables vs. CSV and we can make a v0.5 of CohortGenerator to support these updates.

**Comment by anthonysena** [comment]
Just to add to this issue - the main motivator for this set of changes is to support a generalized `uploadResults()` as was proposed in https://github.com/OHDSI/OhdsiSharing/issues/6. 

In order to achieve this (in my opinion) we need to have a consistent way to: define the results data model, create the results tables, export data in a way that is consistent with the definition of the results model for ease of uploading. At the moment, it appears that there may be inconsistencies in the ways in which we are saving data to CSV across the various HADES packages, including CohortGenerator, CohortDiagnostics, etc.

**Comment by azimov** [comment]
>  I'm also looking at the methods in CohortDiagnostics' Incremental.R file and think that perhaps we should aim to move these into CohortGenerator. Specifically the methods where we write to CSV:
> 
>https://github.com/OHDSI/CohortDiagnostics/blob/main/R/Incremental.R#L144-L222

I don't have a problem doing this but the release for version 3.0.0 has been delayed a lot and includes a lot of core changes. I agree that we should move it to Cohort Generator as it seems natural that there should be a consistent method across HADES packages for incremental tasks, but this can probably wait for version 3.1.0.

**Comment by anthonysena** [comment]
>  I don't have a problem doing this but the release for version 3.0.0 has been delayed a lot and includes a lot of core changes. I agree that we should move it to Cohort Generator as it seems natural that there should be a consistent method across HADES packages for incremental tasks, but this can probably wait for version 3.1.0.

Agreed - I do not want to hold up the release of CohortDiagnostics v3.0.0. I'd propose that I revise this issue or open a new one to note this as a task and aim to move this as part of the v0.5 code base for CohortGenerator. It will be up to you to decide how you want to deprecate that functionality in CohortDiagnostics when ready.

**Comment by anthonysena** [comment]
Closed via #29
