### ISSUE TITLE
Common cohort definition set validator

### ISSUE THREAD

**Issue by azimov** [OHDSI/CohortGenerator#28]
It would be useful to have a common validation of a cohort definition set that can be used in packages to assert that a `cohortDefinitionSet` conforms to the correct properties required in the `data.frame`. Currently, packages have their own definitions which may conflict with one another.

In practice, this can have several properties:

* Assert that the names are correct
* Assert that the field types are correct
* Assert that the set includes json and sql

**Comment by anthonysena** [comment]
This appears to be the same proposal that exists in #21. I'll close this out here and move the conversation into that issue.
