### ISSUE TITLE
Erros [...] CohortGenerator requires the following columns in the settings file: "cohortId", "cohortName".

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/CohortGenerator#35]
Please refer to: https://github.com/OHDSI/SkeletonPredictionStudy/issues/29

**Comment by jreps** [comment]
CohortGenerator also seems linked to this issue: https://github.com/OHDSI/SkeletonPredictionStudy/issues/28

**Comment by lhjohn** [comment]
Just to follow up on this. CohortGenerator has a function `readCsv`, which actually calls `colnames(fileContents) <- SqlRender::snakeCaseToCamelCase(colnames(fileContents))`. The result for the column names should be camel case, but turns out to be something in between. So instead of `cohortId` I get `cohortid`, and instead of `cohortName` I get `cohortname`. Seems to be a problem with SqlRender.

**Comment by lhjohn** [comment]
@anthonysena, are you not calling the wrong function here?

The call in `readCsv()` is `SqlRender::snakeCaseToCamelCase()`, but the `Cohort.csv` has camel case column names, so it should be `SqlRender::camelCaseToSnakeCase()`. Or, are our column names in `Cohort.csv` not standard @jreps?

**Comment by anthonysena** [comment]
Hi @lhjohn - I think `readCsv` is working as expected. For reference, here is the code:

https://github.com/OHDSI/CohortGenerator/blob/5afa6344ad938c9260bb462164b06450a8402322/R/CsvHelper.R#L35-L46

I would expect that `CohortGenerator::readCsv` warns you about column names that are not in snake_case format when reading  `Cohort.csv` with column names like `cohortId`. Let me know if this is not the case and perhaps there is a bug in my regex that aims to detect the casing.

**Comment by anthonysena** [comment]
> I believe the problem in your snippet is line 44, which is always called, even if the `colnames(fileContents)` are already in camel case. This results in "corrupting" the correct camel case to be all lower case.

Yes, this is by design: the contents of the .csv `file` parameter are assumed to be in snake_case which is the HADES standard. The warning message was added to alert you to a casing problem if one exists. Do you get this warning message when reading `Cohort.csv`?

**Comment by lhjohn** [comment]
Yes, I get the warning. But, from the Hades documentation ([here](https://ohdsi.github.io/Hades/codeStyle.html)) I understand that function names and variable names should be in camel case. I would consider column names variable names since they can be accessed with the `$` operator.

Ultimately, I do not really mind whether they are camel case or snake case. If the latter, then we must change `SkeletonPredictionStudy` package, if the former we should change `CohortGenerator`.

**Comment by anthonysena** [comment]
Linking this to #37 - just re-opening for awareness @lhjohn so that we can make the code more flexible to support ways in which study package have stored the cohort settings.
