### ISSUE TITLE
getCohortDefinitionSet does not recognize camel case column names

### ISSUE THREAD

**Issue by andtsouch** [OHDSI/CohortGenerator#40]
Hi, I am running a PatientLevelPrediction5.0.5 study package that is generated by Hydra0.3.0. While executing the package with the execute function provided in the CodeToRun.R, I am getting the following error seen in the print screen attached. However my Cohorts.csv file has the column names with camel case as expected by the function getCohortDefinitionSet. Do you have any idea what might be causing this error? I have the latest version of CohortGenrator0.5.0.
![error_csv_session](https://user-images.githubusercontent.com/59889084/178773774-5aca2f1f-6728-4bf7-9522-7c6e1064b921.jpg)

**Comment by andtsouch** [comment]
Great thank you. I will try to customize the functions used by the study package for now.

**Comment by anthonysena** [comment]
@andtsouch - I've pushed a change to the develop branch that should address this issue. Could you give it a try with your package to see if it clears the error here?

**Comment by andtsouch** [comment]
Thank you, I will test it out and update you.

**Comment by anthonysena** [comment]
Hi - this should now be resolved with the v0.6 release so I'm going to close this issue. If you are still facing problems, please re-open the issue and we can continue the investigation.
