### ISSUE TITLE
Bigquery: Needs explicit cast

### ISSUE THREAD

**Issue by mgkahn** [OHDSI/CohortGenerator#51]
See error from TYPE conversion. Needs explicit cast to integer. Submitted PR #50 with fix 
![CohortGenerator_datatype_error](https://user-images.githubusercontent.com/3923918/180031884-af6800cd-d183-4d99-b075-6a60f1beff9f.PNG)

**Comment by mgkahn** [comment]
Sorry for the delay. I can confirm that the version of CohortGenerator currently pushed to the develop branch runs the OHDSI network study (https://github.com/ohdsi-studies/ReproducibilityRayJAMA2021.git) that triggered the initial bug report  w/o error using BigQuery.

**Comment by anthonysena** [comment]
Thanks for confirming @mgkahn!

**Comment by anthonysena** [comment]
Closed as this was part of the v0.7 release.
