### ISSUE TITLE
Error returned by getCohortDefinitionSet: '' does not exist in current working directory

### ISSUE THREAD

**Issue by atsoham** [OHDSI/CohortGenerator#56]
Hi,
I am trying to execute a PLE (Population Level Estimation) study package generated by Hydra (0.3.0). When I try to run the **execute** function built in **CodeToRun.R**, I get this error. The traceback point to **getCohortDefinitionSet** for returning the error. I believe that the function is trying to locate the **Cohorts.csv** file under inst/ but is unable to find it (even though it is present and has the details of the cohorts). Has anyone encountered this before / knows where the issue is coming from and how to resolve it?

![image](https://user-images.githubusercontent.com/108692536/181519623-d8398b5c-8998-477b-a6e3-1723ab128266.png)
**^ Error message ^**

![image](https://user-images.githubusercontent.com/108692536/181519806-c2ef6a7a-bd72-45bb-9344-f48e0cfe962d.png)
**^ Traceback ^**

![image](https://user-images.githubusercontent.com/108692536/181520038-850167c3-f71f-4b6a-85ff-0c6762c4bbc2.png)
**^ Cohort.csv file ^**

![image](https://user-images.githubusercontent.com/108692536/181521650-25972845-a786-4df5-8f37-d3b6a97ab2e6.png)
**^ Working directory is correct ^**

**Comment by anthonysena** [comment]
Hi - have you built/installed the package prior to running it?

**Comment by atsoham** [comment]
Hey @anthonysena,

Thanks for the tip! I was building and installing the package with **devtools** but on closer inspection, I realised that I was doing it incorrectly. I have corrected my commands and the error issue is resolved.
