### ISSUE TITLE
When cohorts have no inclusion rules, a warning is shown

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortGenerator#57]
https://github.com/OHDSI/CohortGenerator/blob/5afa6344ad938c9260bb462164b06450a8402322/R/CohortStats.R#L130

I think it should just be a note and not warning, because cohort definitions without inclusion rule is valid.

**Comment by anthonysena** [comment]
I am OK with leaving this as a `warning` since this warning is raised in the function `insertInclusionRuleNames` and a warning to let you know that there were no inclusion rules found seems appropriate.
