### ISSUE TITLE
Cohort Subsets

### ISSUE THREAD

**Issue by azimov** [OHDSI/CohortGenerator#67]
We would like to create templates for subsetting cohorts in a reproducible manner.
These subsets should allow simple operations on cohorts in a cohort definition set in a way that allows easy integration with existing packages.

For example, running `CohortDiagnostics` or `CohortMethod` an output cohort subset should just have an Id, start date and end date.

Requirements:

Parameters : `targetOutcomePairs - list of Tuples of ```(I,O)```:
*`I` Input set of target cohort id
*`O` output set of output cohort ids

output Ids must not collide with existing in cohort database/cohort definition set.

Subset classes should be based on operations. The proposed initial design is to use R6 classes.
Each of these should have unique names and identifiers.
All definitions should be json serializable and deserializable in a predictable manner that handles the quirks of working with R.

Initially, these operations should be:

* Cohort Subset operators - subset cohort `x` to only patients contained in `y,z`
* Demographics Subsets Operators - subset to specified demographic criteria (age, gender, race etc)
* Limit subsets - Subset to periods (e.g. a washout period or follow up period, the earliest event per subject)

Random sample subsets have been discussed, however, this implementation may be challenging and isn't an initial requirement (these would need to be reproducible on different database platforms with a random seed etc).

A subset definition should take one or more subset operators and execute them.

Names should map to the original cohort and short and long form human readable names that allow subset operations to be applied.

**Comment by azimov** [comment]
Related to #65

**Comment by anthonysena** [comment]
Adding additional details for the various operations we'd like to support with the subset feature

### Cohort Subset

-  Subset cohort `x` to only patients contained in `{y,z}`. This can be an any/all for the cohorts in `{y,z}`
-  We need to be able to use negation in the cohort subset operator that would return the inverse of the subset rule.
-  Subset cohort operator needs to have a way to specify 8 parameters to define the relationship between the Target (T) cohort start & end date and the Subset cohort (S) cohort start & end. It should following the parameters from an inclusion criteria:
![image](https://user-images.githubusercontent.com/12902366/207949330-af9b317e-d66f-4937-b588-2fbe7357f38e.png)
represented by the JSON:
```json
            "StartWindow": {
              "Start": {
                "Coeff": -1
              },
              "End": {
                "Days": 1,
                "Coeff": 1
              },
              "UseEventEnd": false
            },
            "EndWindow": {
              "Start": {
                "Days": 21,
                "Coeff": 1
              },
              "End": {
                "Coeff": 1
              },
              "UseIndexEnd": true,
              "UseEventEnd": true
            }
```
(Taken from the circe-be JSON)

### Limit Subest

- In addition to the periods mentioned earlier, we'd also like to subset based on the target cohort overlapping a calendar time interval.

### Demographics

We need to make sure that we have race, ethnicity, age (min/max), sex (list of gender_concept_id). In the case of the list of values for demographics, this will be treated as an "any" operation.

**Comment by anthonysena** [comment]
Based on user feedback, we would like to revise the subset functionality such that:

- Subset _operators_ do not require an ID.
- Subset operators can provide a default name based on the parameters. A user can override this default if desired.

**Comment by anthonysena** [comment]
Additional feedback from usage of the subset functionality:

`CohortGenerator::createLimitSubset()` currently requires all arguments to be specified by the user. Could these be optional? So for example, if I just want to set the calendar start and end time, not also require the user to specify priorTime, followUpTime, and limitTo?
