### ISSUE TITLE
Options to add distribute key while creating cohort table

### ISSUE THREAD

**Issue by gowthamrao** [OHDSI/CohortGenerator#69]
Would it be possible to add 

`--HINT DISTRIBUTE ON KEY (subject_id)`

to the create cohort table DDL

https://github.com/OHDSI/CohortGenerator/blob/2f84a104d24c2abef1bc0df8ed891a050c0d80a3/inst/sql/sql_server/CreateCohortTables.sql#L9-L15

**Comment by anthonysena** [comment]
This HINT command is necessary since SqlRender will detect the column name of `subject_id` and include it in the rendered query. See below:

![image](https://user-images.githubusercontent.com/12902366/211396174-c70cd902-ca6a-40e6-af24-3d49dd066778.png)
