### ISSUE TITLE
[Question] Destination CRAN?

### ISSUE THREAD

**Issue by ablack3** [OHDSI/CohortGenerator#77]
Is putting CohortGenerator on CRAN on the roadmap for this package?

**Comment by anthonysena** [comment]
Yes, I would like to get this package on CRAN but have not put it on the roadmap.

**Comment by ablack3** [comment]
Ok thanks, just checking. It is a little tricky to get a package on CRAN that "suggests" another package not on CRAN (e.g. CirceR).

**Comment by anthonysena** [comment]
Thanks for sharing that experience - CirceR is suggested since I use it in the vignettes and perhaps I can revise this when I address #70.

**Comment by gowthamrao** [comment]
Why @anthonysena - any updates on going to CRAN

**Comment by ablack3** [comment]
CirceR is on cran now!

**Comment by anthonysena** [comment]
CohortGenerator is now on CRAN: https://cran.r-project.org/web/packages/CohortGenerator/index.html.
